- hosts: hubot-user
  become: yes
  tasks:
    - name: yum update
      yum: name=* state=latest
      notify:
        - reboot
        - waiting
      lineinfile:
        dest=/etc/selinux/config
        regexp=^SELINUX=
        line=SELINUX=disabled
      notify:
        - reboot
        - waiting
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
    - name: selinux disabled
      selinux: state=disabled
    - name: install vim
      yum: name=vim state=latest
    - name: install bind-utils
      yum: name=bind-utils state=latest
    - name: install wget
      yum: name=wget state=latest
    - name: install git
      yum: name=git state=latest
    - name: install traceroute
      yum: name=traceroute state=latest
    - name: install libselinux-python
      yum: name=libselinux-python state=latest
  handlers:
  - name: reboot
    shell: sleep 2 && shutdown -r now "Ansible updates triggered"
    async: 1
    poll: 0
    ignore_errors: true
  - name: waiting
    local_action: wait_for host={{ inventory_hostname }} port=22 delay=1 timeout=300
    become: false
